---
#
- name: Create Proxmox VM
  community.general.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token }}"
    name: "{{ inventory_hostname | upper }}"
    node: "{{ pve_node }}"
    vmid: "{{ vmid }}"
    agent: 1
    cores: 2
    memory: 2048
    ostype: l26
    scsihw: virtio-scsi-pci
    ide:
      ide2: "{{ cloud_vm_storage_pool }}:cloudinit"
    net:
      net0: "virtio,bridge=vmbr0"
    boot: "order=ide2;scsi0"
  delegate_to: localhost
